# Generated by Django 5.2.7 on 2025-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
