# Generated by Django 5.2.7 on 2025-11-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0005_categoria_page_producto_delete_rubro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-publicado']},
        ),
    ]
