# Generated by Django 5.2.7 on 2025-11-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0006_alter_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
    ]
