# Generated by Django 5.2.7 on 2025-11-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0008_cliente_registrado_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
