# Generated by Django 5.2.7 on 2025-11-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0009_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
